version: 1.0.{build}

image: Ubuntu

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  - java -jar ./artifacts/app-order.jar &

build_script:
  - chmod +x ./gradlew
  - ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации
